/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contacttracing;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandro Palumbo
 */
public class newSerological extends javax.swing.JFrame {

    /**
     * Creates new form newSerological
     */
    public newSerological() {
        initComponents();
        setIcon();
    }
    
    public int getVisit(){
       int idv = 0;
       PreparedStatement st;
        Connection conn;
        ResultSet rs;
        String query = "SELECT MAX(idV) FROM Visit";
        try {
            conn = Database.getDefaultConnection();
            st = conn.prepareStatement(query);
            rs= st.executeQuery();
           
        while(rs.next()){ 
            idv = rs.getInt(1);
        }
        st.close();
        } catch (SQLException ex) {
          Logger.getLogger(newTest.class.getName()).log(Level.SEVERE, null, ex);
        }   
       return idv;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jNegative = new javax.swing.JRadioButton();
        jIGM = new javax.swing.JRadioButton();
        jIGG = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jInsert = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jNegative);
        jNegative.setText("Negative");

        buttonGroup1.add(jIGM);
        jIGM.setText("igM");

        buttonGroup1.add(jIGG);
        jIGG.setText("igG");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Test Sierologico");

        jInsert.setBackground(new java.awt.Color(0, 102, 153));
        jInsert.setText("Inserisci");
        jInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertActionPerformed(evt);
            }
        });

        jDelete.setBackground(new java.awt.Color(204, 0, 0));
        jDelete.setText("Annulla");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Logoff");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jInsert)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDelete))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jNegative)
                            .addGap(36, 36, 36)
                            .addComponent(jIGM)
                            .addGap(43, 43, 43)
                            .addComponent(jIGG)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNegative)
                    .addComponent(jIGG)
                    .addComponent(jIGM))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInsert)
                    .addComponent(jDelete))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
       dispose();
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertActionPerformed
        int idv = getVisit();
        String res = new String();
        
        if(jNegative.isSelected())
            res = "negative";
        if(jIGM.isSelected())
            res =  "igm";
        if(jIGG.isSelected())
            res = "igg";
        
        PreparedStatement st;
        Connection conn;
        String query = "INSERT INTO Serological(id_VSE,Results) VALUES (?,?)";
        try {
           conn = Database.getDefaultConnection();
           st = conn.prepareStatement(query);
           st.setInt(1,idv);
           st.setString(2,res);
           if(st.executeUpdate()>0){
               if(res.equals("igm"))
                    JOptionPane.showMessageDialog(null, "Test sierologico eseguito correttamente.\nPer accertamenti si consiglia di eseguire un tampone naso-faringeo.");
               else
                   JOptionPane.showMessageDialog(null, "Test sierologico eseguito correttamente.");
            dispose();
         }
             st.close();
             } catch (SQLException ex) {
           Logger.getLogger(newSerological .class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jInsertActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this,
            "Contact Tracer\nApplicativo Java per emulare il Tracking del virus Sars-CoV-2"
            + "\nUniversità di Napoli Federico II"
            + "\n\nSviluppatore: Alessandro Palumbo N86001990 ",
            "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconcov.jpg")));
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jDelete;
    private javax.swing.JRadioButton jIGG;
    private javax.swing.JRadioButton jIGM;
    private javax.swing.JButton jInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jNegative;
    // End of variables declaration//GEN-END:variables
}
