/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contacttracing;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alessandro Palumbo
 */
public class ViewSituation extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form ViewSituation
     */
    public ViewSituation() {
        initComponents();
        fillCombo();
        setIcon();
    }
    
    private void fillCombo(){
        PreparedStatement st;
        Connection conn;
        ResultSet rs;
        String query = "SELECT DISTINCT City From Loc";
        try {
            conn = Database.getDefaultConnection();
            st = conn.prepareStatement(query);
            rs= st.executeQuery();
           
            while(rs.next()){ 
               String city = rs.getString(1);
               comboCity.addItem(city);
            }
            st.close();
        } catch (SQLException ex) {
          Logger.getLogger(ViewTracking.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboCity = new javax.swing.JComboBox<>();
        viewCity = new javax.swing.JButton();
        viewItaly = new javax.swing.JButton();
        qoLabel = new javax.swing.JLabel();
        qcLabel = new javax.swing.JLabel();
        dLabel = new javax.swing.JLabel();
        hLabel = new javax.swing.JLabel();
        tLabel = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Situazione per citta");

        jLabel2.setText("Situazione in Italia");

        viewCity.setBackground(new java.awt.Color(0, 102, 153));
        viewCity.setText("Visualizza");
        viewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCityActionPerformed(evt);
            }
        });

        viewItaly.setBackground(new java.awt.Color(0, 102, 153));
        viewItaly.setText("Visualizza");
        viewItaly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItalyActionPerformed(evt);
            }
        });

        qoLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        qoLabel.setText("0");

        qcLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        qcLabel.setText("0");

        dLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dLabel.setText("0");

        hLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        hLabel.setText("0");

        tLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tLabel.setText("0");

        jBack.setBackground(new java.awt.Color(204, 0, 0));
        jBack.setText("Indietro");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        jLabel8.setText("Quarantena Ospedale");

        jLabel9.setText("Quarantena Casa");

        jLabel10.setText("Deceduti");

        jLabel11.setText("Guariti");

        jLabel12.setText("Test Totali");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconcov.jpg"))); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Logoff");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewItaly)
                        .addGap(107, 107, 107))))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(qoLabel)
                        .addGap(117, 117, 117)
                        .addComponent(qcLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(dLabel)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(60, 60, 60)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(hLabel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(tLabel)))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addGap(321, 321, 321))))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewItaly))
                        .addGap(18, 18, 18)
                        .addComponent(viewCity))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qcLabel)
                    .addComponent(dLabel)
                    .addComponent(hLabel)
                    .addComponent(tLabel)
                    .addComponent(qoLabel))
                .addGap(35, 35, 35)
                .addComponent(jBack)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCityActionPerformed
       PreparedStatement st;
       Connection conn;
       ResultSet rs;
       String cc = comboCity.getSelectedItem().toString();
       String query = "SELECT qc.qp,qo.qo,vd.hd,vh.hh,tv.qv FROM quarantenacasa qc, quarantenaospedale qo,vdeceased vd,vhealed vh,totalv tv"
                       +" WHERE qc.City='"+cc+"' AND qo.City='"+cc+"' AND vd.City='"+cc+"' AND vh.City='"+cc+"' AND tv.City='"+cc+"'";
       try {
            conn = Database.getDefaultConnection();
              st = conn.prepareStatement(query);
              rs= st.executeQuery();
           
            while(rs.next()){ 
               String qc = rs.getString(1);
               String qo =rs.getString(2);
               String d = rs.getString(3);
               String g = rs.getString(4);
               String t = rs.getString(5);
               qoLabel.setText(qo);
               qcLabel.setText(qc);
               dLabel.setText(d);
               hLabel.setText(g);
               tLabel.setText(t);
            }
            st.close();
        } catch (SQLException ex) {
          Logger.getLogger(ViewTracking.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_viewCityActionPerformed

    private void viewItalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItalyActionPerformed
       PreparedStatement st;
       Connection conn;
       ResultSet rs;
       String query = " SELECT * FROM current_s";
        try {
            conn = Database.getDefaultConnection();
              st = conn.prepareStatement(query);
              rs= st.executeQuery();
           
            while(rs.next()){ 
               String qc = rs.getString(1);
               String qo =rs.getString(2);
               String d = rs.getString(3);
               String g = rs.getString(4);
               String t = rs.getString(5);
               qoLabel.setText(qo);
               qcLabel.setText(qc);
               dLabel.setText(d);
               hLabel.setText(g);
               tLabel.setText(t);
            }
            st.close();
        } catch (SQLException ex) {
          Logger.getLogger(ViewTracking.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_viewItalyActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
       MainCT mc;
       mc = new MainCT(1);
       mc.setVisible(true);     
       dispose();
    }//GEN-LAST:event_jBackActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this,
            "Contact Tracer\nApplicativo Java per emulare il Tracking del virus Sars-CoV-2"
            + "\nUniversità di Napoli Federico II"
            + "\n\nSviluppatore: Alessandro Palumbo N86001990 ",
            "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconcov.jpg")));
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCity;
    private javax.swing.JLabel dLabel;
    private javax.swing.JLabel hLabel;
    private javax.swing.JButton jBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel qcLabel;
    private javax.swing.JLabel qoLabel;
    private javax.swing.JLabel tLabel;
    private javax.swing.JButton viewCity;
    private javax.swing.JButton viewItaly;
    // End of variables declaration//GEN-END:variables
}
